<?php
/**
 * PEP Capping 2017 Algozzine's Class
 *
 * Displays Monthly Reports.
 *
 * This page will display the information required for Monthly
 * Reports, formatted into tables. The desired month and year can be
 * selected by the drop down menus at the top and the 'Generate Report'
 * button will query the database and update the tables below.
 *
 * @author Rafael Mormol & Daniel Ahl
 * @copyright 2017 Marist College
 * @version 0.1.5
 * @since 0.1.4
 */
    global $params, $route, $view;
    include('header.php'); 
    ?>
<div class="container">
    <div class="container pt-5 pb-4">
        <div class="row" style="margin-bottom: 1%">
            <div class="col">
                <form>
                    <div class="form-group">
                        <select class="form-control" id="month">
                            <option>January</option>
                            <option>February</option>
                            <option>March</option>
                            <option>April</option>
                            <option>May</option>
                            <option>June</option>
                            <option>July</option>
                            <option>August</option>
                            <option>September</option>
                            <option>October</option>
                            <option>November</option>
                            <option>December</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="col">
                <form>
                    <div class="form-group">
                        <select class="form-control" id="year">
                            <option>2017</option>
                            <option>2016</option>
                            <option>2015</option>
                            <option>2014</option>
                        </select>
                    </div>
                </form>
            </div>
        </div>
        <div class="row pb-5">
            <div class="col"></div>
            <div class="col-centered">
                <p>
                    <a class="btn cpca" href="#">Generate Report</a>
                </p>
            </div>
            <div class="col"></div>
        </div>
    </div>
    <div class="page-header py-3">
        <h1 class="text-center">
            October 2017
        </h1>
    </div>
    <br />
    <h5 class="text-center">
        Number Served
    </h5>
    <br />
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>
                    Current Month
                </th>
                <th>
                    Newly Served
                </th>
                <th>
                    Duplicate Served
                </th>
                <th>
                    YTD
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    302
                </td>
                <td>
                    121
                </td>
                <td>
                    181
                </td>
                <td>
                    996
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <h5 class="text-center">
        Demographics of Adults
    </h5>
    <br />
    <h6 class="text-center">
        Gender
    </h6>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>
                </th>
                <th>
                    Current Month
                </th>
                <th>
                    Newly Served
                </th>
                <th>
                    Duplicate Served
                </th>
                <th>
                    YTD
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <b>
                    Male
                    </b>
                </td>
                <td>
                    144
                </td>
                <td>
                    58
                </td>
                <td>
                    86
                </td>
                <td>
                    560
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Female
                    </b>
                </td>
                <td>
                    157
                </td>
                <td>
                    63
                </td>
                <td>
                    94
                </td>
                <td>
                    436
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <h6 class="text-center">
        Age
    </h6>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>
                </th>
                <th>
                    Current Month
                </th>
                <th>
                    Newly Served
                </th>
                <th>
                    Duplicate Served
                </th>
                <th>
                    YTD
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <b>
                    20-40
                    </b>
                </td>
                <td>
                    204
                </td>
                <td>
                    82
                </td>
                <td>
                    122
                </td>
                <td>
                    618
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    41-64
                    </b>
                </td>
                <td>
                    97
                </td>
                <td>
                    39
                </td>
                <td>
                    58
                </td>
                <td>
                    377
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    65+
                    </b>
                </td>
                <td>
                    1
                </td>
                <td>
                </td>
                <td>
                    1
                </td>
                <td>
                    1
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <h6 class="text-center">
        Ethnicity
    </h6>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>
                </th>
                <th>
                    Current Month
                </th>
                <th>
                    Newly Served
                </th>
                <th>
                    Duplicate Served
                </th>
                <th>
                    YTD
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <b>
                    Caucasian
                    </b>
                </td>
                <td>
                    144
                </td>
                <td>
                    58
                </td>
                <td>
                    86
                </td>
                <td>
                    450
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    African American
                    </b>
                </td>
                <td>
                    78
                </td>
                <td>
                    31
                </td>
                <td>
                    47
                </td>
                <td>
                    288
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Multi Racial
                    </b>
                </td>
                <td>
                    11
                </td>
                <td>
                    5
                </td>
                <td>
                    6
                </td>
                <td>
                    30
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Latino
                    </b>
                </td>
                <td>
                    59
                </td>
                <td>
                    24
                </td>
                <td>
                    35
                </td>
                <td>
                    211
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Pacific Islander
                    </b>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Native American
                    </b>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    Other
                    </b>
                </td>
                <td>
                    10
                </td>
                <td>
                    3
                </td>
                <td>
                    7
                </td>
                <td>
                    17
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <h5 class="text-center">
        Zip Code Data
    </h5>
    <h6 class="text-center">
        For use by PSP, ISP, TLC, & CAC only
    </h6>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th>
                    Zip
                </th>
                <th>
                    Town
                </th>
                <th>
                    Current Month
                </th>
                <th>
                    Newly Served
                </th>
                <th>
                    Duplicate Served
                </th>
                <th>
                    YTD
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <b>
                    12501 
                    </b>
                </td>
                <td>
                    <b>
                    Amenia
                    </b>
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    0
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12504
                    </b>
                </td>
                <td>
                    <b>
                    Annandale
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12506
                    </b>
                </td>
                <td>
                    <b>
                    Bangall
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12507
                    </b>
                </td>
                <td>
                    <b>
                    Barrytown
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12508
                    </b>
                </td>
                <td>
                    <b>
                    Beacon
                    </b>
                </td>
                <td>
                    9
                </td>
                <td>
                    4
                </td>
                <td>
                    5
                </td>
                <td>
                    16
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12514
                    </b>
                </td>
                <td>
                    <b>
                    Clinton Corners
                    </b>
                </td>
                <td>
                    1
                </td>
                <td></td>
                <td>
                    1
                </td>
                <td>
                    1
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12522
                    </b>
                </td>
                <td>
                    <b>
                    Dover Plains
                    </b>
                </td>
                <td>
                    6
                </td>
                <td>
                    3
                </td>
                <td>
                    3
                </td>
                <td>
                    7
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12524
                    </b>
                </td>
                <td>
                    <b>
                    Fishkill
                    </b>
                </td>
                <td>
                    2
                </td>
                <td>
                    1
                </td>
                <td>
                    1
                </td>
                <td>
                    11
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12531
                    </b>
                </td>
                <td>
                    <b>
                    Holmes
                    </b>
                </td>
                <td>
                    1
                </td>
                <td>
                    1
                </td>
                <td>
                </td>
                <td>
                    1
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12533
                    </b>
                </td>
                <td>
                    <b>
                    Hopewell Junction
                    </b>
                </td>
                <td>
                    3
                </td>
                <td>
                    1
                </td>
                <td>
                    2
                </td>
                <td>
                    8
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12537
                    </b>
                </td>
                <td>
                    <b>
                    Hughsonville
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12538
                    </b>
                </td>
                <td>
                    <b>
                    Hyde Park
                    </b>
                </td>
                <td>
                    9
                </td>
                <td>
                    5
                </td>
                <td>
                    4
                </td>
                <td>
                    16
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12540
                    </b>
                </td>
                <td>
                    <b>
                    LaGrangeville
                    </b>
                </td>
                <td>
                </td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    1
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12545
                    </b>
                </td>
                <td>
                    <b>
                    Millbrook
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    1
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12546
                    </b>
                </td>
                <td>
                    <b>
                    Millerton
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12564
                    </b>
                </td>
                <td>
                    <b>
                    Pawling
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    6
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12567
                    </b>
                </td>
                <td>
                    <b>
                    Pine Plains
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    1
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12569
                    </b>
                </td>
                <td>
                    <b>
                    Pleasant Valley
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    5
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12570
                    </b>
                </td>
                <td>
                    <b>
                    Poughquag
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12571
                    </b>
                </td>
                <td>
                    <b>
                    Red Hook
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    6
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12572
                    </b>
                </td>
                <td>
                    <b>
                    Rhinebeck
                    </b>
                </td>
                <td>
                    142
                </td>
                <td>
                    60
                </td>
                <td>
                    82
                </td>
                <td>
                    588
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12574
                    </b>
                </td>
                <td>
                    <b>
                    Rhinecliff
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12578
                    </b>
                </td>
                <td>
                    <b>
                    Salt Point
                    </b>
                </td>
                <td>
                    2
                </td>
                <td>
                    1
                </td>
                <td>
                    1
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12580
                    </b>
                </td>
                <td>
                    <b>
                    Staatsburg
                    </b>
                </td>
                <td>
                </td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    4
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12581
                    </b>
                </td>
                <td>
                    <b>
                    Standfordville
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    2
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12582
                    </b>
                </td>
                <td>
                    <b>
                    Stormville
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12583
                    </b>
                </td>
                <td>
                    <b>
                    Tivoli
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12585
                    </b>
                </td>
                <td>
                    <b>
                    Verbank
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12590
                    </b>
                </td>
                <td>
                    <b>
                    Wappingers Falls
                    </b>
                </td>
                <td>
                    12
                </td>
                <td>
                    5
                </td>
                <td>
                    7
                </td>
                <td>
                    31
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12592
                    </b>
                </td>
                <td>
                    <b>
                    Wassaic
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12594
                    </b>
                </td>
                <td>
                    <b>
                    Wingdale
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    5
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12601
                    </b>
                </td>
                <td>
                    <b>
                    City of Pok.
                    </b>
                </td>
                <td>
                    73
                </td>
                <td>
                    33
                </td>
                <td>
                    40
                </td>
                <td>
                    223
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12602
                    </b>
                </td>
                <td>
                    <b>
                    Pok. P.O. Boxes
                    </b>
                </td>
                <td>
                    3
                </td>
                <td>
                    1
                </td>
                <td>
                    2
                </td>
                <td>
                    12
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12603
                    </b>
                </td>
                <td>
                    <b>
                    Town of Pok.
                    </b>
                </td>
                <td>
                    12
                </td>
                <td>
                    2
                </td>
                <td>
                    10
                </td>
                <td>
                    27
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    12504
                    </b>
                </td>
                <td>
                    <b>
                    Town of Pok.
                    </b>
                </td>
                <td></td>
                <td></td>
                <td>
                    0
                </td>
                <td>
                    0
                </td>
            </tr>
            <tr>
                <td>
                    <b>
                    </b>
                </td>
                <td>
                    <b>
                    Other
                    </b>
                </td>
                <td>
                    27
                </td>
                <td>
                    5
                </td>
                <td>
                    22
                </td>
                <td>
                    17
                </td>
            </tr>
        </tbody>
    </table>
    <h5 class="text-center">
        Parenting Services
    </h5>
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th></th>
                <th>Current Month</th>
                <th>New</th>
                <th>Duplicate</th>
                <th>YTD</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Children Served Indirectly</th>
                <td>615</td>
                <td>241</td>
                <td>374</td>
                <td>1386</td>
            </tr>
        </tbody>
    </table>
</div>
<?php include('footer.php'); ?>